<?php
namespace Database\Seeders;
use App\Models\{SiteSetting,CeremonyService,Package,MenuItem,GalleryItem,Testimonial,Post,Faq};
use Illuminate\Database\Seeder;
class DatabaseSeeder extends Seeder { public function run():void{
 SiteSetting::create(['site_name'=>'تالارتو','phone'=>'021-00000000','whatsapp'=>'09000000000','instagram'=>'talarto','address'=>'تهران — آدرس مجموعه از پنل مدیریت قابل ویرایش است.','hero_title'=>'جایی برای ماندگارترین شب زندگی','hero_subtitle'=>'برگزاری عروسی، عقد، نامزدی، تولد و مراسم خصوصی با طراحی اختصاصی، پذیرایی حرفه‌ای و برنامه‌ریزی دقیق.','about_title'=>'یک مجموعه، یک تیم، یک اجرای یکپارچه','about_body'=>'تالارتو وب‌سایت اختصاصی مجموعه است؛ از بازدید اولیه و انتخاب منو تا چیدمان، نورپردازی و اجرای روز مراسم، همه‌چیز از یک مسیر هماهنگ می‌شود.','hero_image'=>'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=90','about_image'=>'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85','capacity_min'=>50,'capacity_max'=>700,'parking_capacity'=>180,'amenities'=>['پارکینگ اختصاصی','سالن عقد','نورپردازی حرفه‌ای','سیستم صوتی','اتاق عروس و داماد','گل‌آرایی','فضای عکاسی'],'seo_title'=>'تالارتو | تالار عروسی، عقد، نامزدی و تولد','seo_description'=>'معرفی مجموعه تالارتو، خدمات مراسم، منو و پکیج‌ها، گالری، تقویم تاریخ‌های قابل رزرو و درخواست بازدید.']);
 $services=[
 ['عروسی','wedding','مراسم عروسی','برنامه‌ریزی و اجرای کامل جشن عروسی با چیدمان اختصاصی، نورپردازی، پذیرایی و هماهنگی تیم اجرایی.','https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85','✦'],
 ['مراسم عقد','aghd','عقد و عقدکنان','چیدمان سفره عقد، گل‌آرایی، پذیرایی و فضای عکاسی برای عقد رسمی و جشن عقد.','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1400&q=85','◇'],
 ['نامزدی','engagement','جشن نامزدی','اجرای جشن نامزدی صمیمی یا رسمی با طراحی متناسب تعداد مهمان و سبک مراسم.','https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1400&q=85','♡'],
 ['تولد','birthday','جشن تولد','مناسب تولد بزرگسال و کودک، میز کیک، تم اختصاصی، موسیقی و پذیرایی.','https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1400&q=85','☆'],
 ['مراسم خصوصی','private-event','مراسم خصوصی','دورهمی خانوادگی، سالگرد، جشن فارغ‌التحصیلی و مناسبت‌های خصوصی.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85','○'],
 ['همایش و مراسم شرکتی','corporate','مراسم شرکتی','چیدمان رسمی، پذیرایی، سیستم صوتی و اجرای مناسب رویدادهای سازمانی.','https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1400&q=85','□']];
 foreach($services as $i=>$s)CeremonyService::create(['title'=>$s[0],'slug'=>$s[1],'short_description'=>$s[2],'description'=>$s[3],'image'=>$s[4],'icon'=>$s[5],'sort_order'=>$i,'active'=>true]);
 $packages=[
 ['پکیج کلاسیک','classic','برای مراسم جمع‌وجور و شیک',25000000,850000,80,['ورودی و سالن','پذیرایی پایه','نورپردازی سالن','چیدمان میزها'],false],
 ['پکیج ویژه','special','تعادل کامل بین کیفیت و خدمات',45000000,1250000,100,['ورودی و سالن','منوی کامل پذیرایی','گل‌آرایی میزها','نورپردازی حرفه‌ای','اتاق عقد یا جایگاه ویژه'],true],
 ['پکیج تشریفاتی','ceremonial','اجرای کامل با جزئیات اختصاصی',75000000,1750000,120,['طراحی اختصاصی مراسم','منوی تشریفاتی','گل‌آرایی و دیزاین ویژه','نور و صدای حرفه‌ای','هماهنگ‌کننده اختصاصی مراسم'],false]];
 foreach($packages as $i=>$p)Package::create(['title'=>$p[0],'slug'=>$p[1],'subtitle'=>$p[2],'base_price'=>$p[3],'per_guest_price'=>$p[4],'min_guests'=>$p[5],'description'=>'قیمت نهایی پس از انتخاب تاریخ، تعداد مهمان و خدمات جانبی اعلام می‌شود.','features'=>$p[6],'featured'=>$p[7],'active'=>true,'sort_order'=>$i]);
 $menu=[['غذای اصلی','چلوکباب لقمه مخصوص',690000],['غذای اصلی','زرشک پلو با مرغ مجلسی',590000],['غذای اصلی','باقالی پلو با گوشت',980000],['پیش‌غذا','سوپ ویژه مراسم',95000],['پیش‌غذا','سالاد فصل و سس مخصوص',120000],['دسر','دسر روز',140000],['نوشیدنی','پکیج نوشیدنی سرد و گرم',165000],['پذیرایی','میوه و شیرینی درجه یک',290000]];
 foreach($menu as $i=>$m)MenuItem::create(['category'=>$m[0],'title'=>$m[1],'description'=>'قابل انتخاب و شخصی‌سازی بر اساس نوع مراسم.','price_per_guest'=>$m[2],'active'=>true,'sort_order'=>$i]);
 $imgs=['https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85'];
 foreach($imgs as $i=>$img)GalleryItem::create(['title'=>'نمای مجموعه '.($i+1),'category'=>$i<3?'سالن':'مراسم','image'=>$img,'active'=>true,'sort_order'=>$i]);
 Testimonial::insert([['name'=>'مریم و علی','event_type'=>'عروسی','body'=>'هماهنگی تیم و نظم اجرای مراسم برای ما مهم‌ترین بخش بود و همه‌چیز طبق برنامه پیش رفت.','rating'=>5,'status'=>'approved','created_at'=>now(),'updated_at'=>now()],['name'=>'سارا','event_type'=>'عقد','body'=>'فضای عقد و پذیرایی بسیار مرتب بود و تیم مجموعه در تمام مراحل همراهی کرد.','rating'=>5,'status'=>'approved','created_at'=>now(),'updated_at'=>now()]]);
 Post::create(['title'=>'چطور تالار مناسب مراسم را انتخاب کنیم؟','slug'=>'how-to-choose-venue','excerpt'=>'ظرفیت، دسترسی، منو، تاریخ و بودجه پنج عامل اصلی انتخاب فضای مناسب هستند.','body'=>'برای انتخاب فضای مراسم ابتدا تعداد مهمان را مشخص کنید. سپس دسترسی، ظرفیت واقعی، نوع چیدمان، کیفیت منو و خدمات جانبی را بررسی کنید. بازدید حضوری پیش از قرارداد کمک می‌کند تصمیم دقیق‌تری بگیرید.','cover_image'=>$imgs[0],'meta_title'=>'راهنمای انتخاب تالار مناسب','meta_description'=>'راهنمای عملی انتخاب تالار و فضای مراسم بر اساس ظرفیت، بودجه و خدمات.','published_at'=>now()]);
 $faqs=[['برای رزرو تاریخ چه کاری لازم است؟','ابتدا فرم رزرو یا بازدید را ثبت کنید؛ پس از بررسی ظرفیت، هماهنگی نهایی انجام می‌شود.'],['آیا امکان تست غذا وجود دارد؟','بسته به پکیج و زمان قرارداد، تست منو با هماهنگی قبلی انجام می‌شود.'],['آیا می‌توان منو را شخصی‌سازی کرد؟','بله، آیتم‌های منو و خدمات جانبی بر اساس نوع مراسم و بودجه قابل تغییر هستند.'],['برای عقد و نامزدی هم رزرو دارید؟','بله، مجموعه برای عروسی، عقد، نامزدی، تولد و مراسم خصوصی قابل رزرو است.']];
 foreach($faqs as $i=>$f)Faq::create(['question'=>$f[0],'answer'=>$f[1],'sort_order'=>$i,'active'=>true]);
 }}
