@extends('layouts.app')
@section('title',$siteSettings?->seo_title ?: 'تالارتو | برگزاری مراسم')
@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">مجموعه اختصاصی برگزاری مراسم</span><h1>{{ $siteSettings?->hero_title }}</h1><p>{{ $siteSettings?->hero_subtitle }}</p><div class="hero-actions"><a class="btn" href="{{ route('reservation') }}">بررسی تاریخ و رزرو</a><a class="btn ghost" href="{{ route('calculator') }}">محاسبه هزینه</a></div><div class="trust"><span>✓ بازدید حضوری</span><span>✓ منوی قابل شخصی‌سازی</span><span>✓ تقویم شمسی</span></div></div><div class="hero-visual"><img src="{{ $siteSettings?->hero_image ?: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1600&q=90' }}" alt="فضای مراسم تالارتو"><div class="hero-card"><b>یک مجموعه برای تمام مراسم‌ها</b><span>عروسی · عقد · نامزدی · تولد</span></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">خدمات مجموعه</span><h2>هر مراسم، طراحی متناسب خودش</h2></div><a href="{{ route('services.index') }}">مشاهده همه</a></div><div class="service-grid">@foreach($services as $s)<a class="service-card" href="{{ route('services.show',$s) }}"><img src="{{ $s->image }}" alt="{{ $s->title }}"><div><i>{{ $s->icon }}</i><h3>{{ $s->title }}</h3><p>{{ $s->short_description }}</p></div></a>@endforeach</div></div></section>
<section class="section alt" id="calculator"><div class="container split"><div><span class="eyebrow">قیمت‌گذاری شفاف</span><h2>هزینه مراسم را از موتور قیمت حساب کن</h2><p>تاریخ، سانس، پکیج، تعداد مهمان و منو در سرور بررسی و مبلغ برآوردی محاسبه می‌شود.</p><a class="btn" href="{{ route('calculator') }}">ورود به محاسبه‌گر دقیق</a></div><div class="visit-box"><h3>مبلغ قرارداد چگونه تعیین می‌شود؟</h3><p>انتخاب پکیج و خدمات، قوانین تاریخ و ظرفیت مجموعه مبنای محاسبه هستند. مبلغ رزرو هنگام ثبت در پیش‌فاکتور نسخه‌دار ذخیره می‌شود.</p></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">پکیج‌ها</span><h2>سه سطح برای سه نوع برنامه</h2></div><a href="{{ route('packages') }}">جزئیات پکیج‌ها</a></div><div class="package-grid">@foreach($packages as $p)<article class="package-card @if($p->featured) featured @endif">@if($p->featured)<span class="ribbon">پیشنهادی</span>@endif<h3>{{ $p->title }}</h3><p>{{ $p->subtitle }}</p><div class="price">از {{ number_format($p->base_price) }} <small>تومان</small></div><ul>@foreach($p->features??[] as $f)<li>✓ {{ $f }}</li>@endforeach</ul><a class="btn ghost full" href="{{ route('reservation',['package'=>$p->id]) }}">انتخاب این پکیج</a></article>@endforeach</div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><div><span class="eyebrow">گالری واقعی مجموعه</span><h2>فضا را قبل از بازدید ببین</h2></div><a href="{{ route('gallery') }}">مشاهده گالری</a></div><div class="mosaic">@foreach($gallery as $g)<button class="gallery-button" data-gallery-src="{{ $g->image }}"><img src="{{ $g->image }}" alt="{{ $g->title }}"></button>@endforeach</div></div></section>
<section class="section"><div class="container split"><div><span class="eyebrow">تقویم مراسم</span><h2>تاریخ پیشنهادی‌ات را انتخاب کن</h2><p>تقویم شمسی برای انتخاب تاریخ طراحی شده و روزهای رزروشده یا مسدود قابل انتخاب نیستند.</p><div class="calendar-demo"><input class="jalali-input" data-jalali-picker data-blocked='@json($blockedDates)' readonly placeholder="انتخاب تاریخ شمسی"></div><a class="btn" href="{{ route('reservation') }}">ثبت درخواست رزرو</a></div><div class="visit-box"><span class="eyebrow">بازدید حضوری</span><h3>قبل از تصمیم، مجموعه را از نزدیک ببین</h3><p>برای بازدید سالن، چیدمان‌ها و هماهنگی درباره منو، یک زمان پیشنهادی ثبت کن.</p><form method="post" action="{{ route('visit.store') }}">@csrf<div class="grid2"><input name="name" placeholder="نام و نام خانوادگی" required><input name="mobile" placeholder="0912..." required><input name="preferred_date_jalali" class="jalali-input" data-jalali-picker readonly placeholder="تاریخ پیشنهادی" required><input name="guest_count" type="number" placeholder="تعداد تقریبی مهمان"></div><textarea name="message" placeholder="توضیحات" rows="3"></textarea><button class="btn">درخواست بازدید</button></form></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><div><span class="eyebrow">تجربه مهمان‌ها</span><h2>نظر کسانی که مراسمشان را اینجا برگزار کردند</h2></div></div><div class="testimonial-grid">@foreach($testimonials as $t)<blockquote><div class="stars">{{ str_repeat('★',$t->rating) }}</div><p>«{{ $t->body }}»</p><footer><b>{{ $t->name }}</b><span>{{ $t->event_type }}</span></footer></blockquote>@endforeach</div></div></section>
<section class="section"><div class="container review-split"><div><span class="eyebrow">نظر شما</span><h2>تجربه مراسمتان را ثبت کنید</h2><p>نظر پس از بررسی مدیر سایت منتشر می‌شود.</p></div><form class="main-form" method="post" action="{{ route('review.store') }}">@csrf<div class="grid2"><input name="name" placeholder="نام" required><select name="event_type"><option>عروسی</option><option>عقد</option><option>نامزدی</option><option>تولد</option><option>مراسم خصوصی</option></select><select name="rating" required><option value="5">۵ ستاره</option><option value="4">۴ ستاره</option><option value="3">۳ ستاره</option><option value="2">۲ ستاره</option><option value="1">۱ ستاره</option></select></div><textarea name="body" rows="4" minlength="10" placeholder="نظر شما" required></textarea><button class="btn">ثبت نظر</button></form></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">مجله مراسم</span><h2>راهنمای برنامه‌ریزی بهتر</h2></div><a href="{{ route('blog.index') }}">همه مقالات</a></div><div class="post-grid">@foreach($posts as $p)<a class="post-card" href="{{ route('blog.show',$p) }}"><img src="{{ $p->cover_image }}" alt="{{ $p->title }}"><div><small>{{ \Morilog\Jalali\Jalalian::fromDateTime($p->published_at)->format('Y/m/d') }}</small><h3>{{ $p->title }}</h3><p>{{ $p->excerpt }}</p></div></a>@endforeach</div></div></section>
<div class="gallery-modal" data-gallery-modal><button data-gallery-close>×</button><img alt="نمای بزرگ"></div>
@endsection
