@extends('layouts.app')
@section('title',($reservation->exists?'ویرایش مراسم':'مراسم جدید').' | تالارتو')
@section('content')
<section class="account-head"><div class="container"><div><span class="eyebrow">{{ $reservation->exists?'ویرایش انتخاب‌ها':'رزرو آنلاین' }}</span><h1>{{ $reservation->exists?'جزئیات مراسم را اصلاح کنید':'مراسم خودت را بساز' }}</h1><p>قیمت سمت سرور محاسبه و همراه جزئیات همان لحظه ذخیره می‌شود.</p></div><a class="account-back" href="{{ $reservation->exists?route('account.reservations.show',$reservation):route('account.dashboard') }}">بازگشت</a></div></section>
<section class="section booking-builder"><div class="container booking-layout">
<form class="booking-form" data-price-form data-preview-url="{{ route('account.price-preview') }}" method="post" action="{{ $reservation->exists?route('account.reservations.update',$reservation):route('account.reservations.store') }}">@csrf @if($reservation->exists)@method('PUT')@endif
<section class="form-section"><div class="form-section-head"><span>01</span><div><h2>اطلاعات مراسم</h2><p>تاریخ، سانس و تعداد مهمان را مشخص کنید.</p></div></div><div class="grid2"><label>نوع مراسم<select name="event_type" required>@foreach(['عروسی','عقد','نامزدی','تولد','مراسم خصوصی','مراسم شرکتی'] as $e)<option value="{{ $e }}" @selected(old('event_type',$reservation->event_type?:'عروسی')===$e)>{{ $e }}</option>@endforeach</select></label><label>تاریخ شمسی<input name="event_date_jalali" class="jalali-input" data-jalali-picker data-blocked='@json($blockedDates)' value="{{ old('event_date_jalali',$reservation->date_jalali) }}" readonly placeholder="انتخاب تاریخ" required></label><label>سانس<select name="time_slot" required><option value="day" @selected(old('time_slot',$reservation->time_slot?:'night')==='day')>روز</option><option value="night" @selected(old('time_slot',$reservation->time_slot?:'night')==='night')>شب</option></select></label><label>تعداد مهمان<input type="number" name="guest_count" min="10" max="5000" value="{{ old('guest_count',$reservation->guest_count?:100) }}" required></label><label>تعداد کودک <small>اختیاری</small><input type="number" name="child_count" min="0" max="1000" value="{{ old('child_count',$reservation->child_count?:0) }}"></label></div></section>
<section class="form-section"><div class="form-section-head"><span>02</span><div><h2>پکیج پایه</h2><p>پکیج نقطه شروع قیمت و خدمات مراسم است.</p></div></div><div class="choice-grid">@foreach($packages as $p)<label class="choice-card"><input type="radio" name="package_id" value="{{ $p->id }}" @checked((int)old('package_id',$reservation->package_id?:$packages->first()?->id)===$p->id) required><div><b>{{ $p->title }}</b><span>{{ $p->subtitle }}</span><strong>{{ number_format($p->base_price) }} پایه</strong><small>+ {{ number_format($p->per_guest_price) }} تومان / مهمان</small></div></label>@endforeach</div></section>
<section class="form-section"><div class="form-section-head"><span>03</span><div><h2>منوی پذیرایی</h2><p>چند آیتم را همزمان انتخاب کنید.</p></div></div>@foreach($menuItems as $category=>$group)<div class="option-group"><h3>{{ $category }}</h3><div class="option-list">@foreach($group as $m)<label class="line-choice"><input type="checkbox" name="menu_items[]" value="{{ $m->id }}" @checked(in_array($m->id,old('menu_items',$selectedMenu)))><span><b>{{ $m->title }}</b><small>{{ $m->description }}</small></span><strong>{{ number_format($m->price_per_guest) }} / نفر</strong></label>@endforeach</div></div>@endforeach</section>
@php($oldAddons=old('addons',$selectedAddons))
<section class="form-section"><div class="form-section-head"><span>04</span><div><h2>خدمات اضافه</h2><p>خدمات ثابت و نفرمحور را روشن/خاموش کنید؛ برای میز، ساعت و تعداد مقدار دقیق وارد کنید.</p></div></div>@forelse($addons as $category=>$group)<div class="option-group"><h3>{{ $category }}</h3><div class="addon-grid">@foreach($group as $a)@php($hasAddon=array_key_exists($a->id,$oldAddons)||array_key_exists((string)$a->id,$oldAddons);$qty=$oldAddons[$a->id]??$oldAddons[(string)$a->id]??1)<div class="addon-card {{ in_array($a->pricing_type,['fixed','per_guest','included'])?'addon-toggle-card':'' }}"><label class="addon-enable"><input type="checkbox" data-addon-toggle="{{ $a->id }}" @checked($hasAddon)><span><b>{{ $a->title }}</b><p>{{ $a->description }}</p><small>{{ ['fixed'=>'قیمت ثابت','per_guest'=>'به‌ازای مهمان','per_table'=>'به‌ازای میز','per_hour'=>'ساعتی','quantity'=>'تعدادی','included'=>'شامل / رایگان'][$a->pricing_type]??$a->pricing_type }} · {{ number_format($a->unit_price) }} تومان</small></span></label>@if(in_array($a->pricing_type,['fixed','per_guest','included']))<input type="hidden" name="addons[{{ $a->id }}]" value="1" data-addon-qty="{{ $a->id }}" @disabled(!$hasAddon)>@else<label>{{ $a->pricing_type==='per_table'?'تعداد میز':($a->pricing_type==='per_hour'?'ساعت':'تعداد') }}<input type="number" step="{{ $a->pricing_type==='per_hour'?'0.5':'1' }}" min="{{ max(1,(float)$a->min_quantity) }}" max="{{ $a->max_quantity?:999 }}" name="addons[{{ $a->id }}]" value="{{ $qty ?: 1 }}" data-addon-qty="{{ $a->id }}" @disabled(!$hasAddon)></label>@endif</div>@endforeach</div></div>@empty<p class="muted">هنوز خدمت اضافه‌ای از پنل مدیریت تعریف نشده است.</p>@endforelse</section>
<section class="form-section"><div class="form-section-head"><span>05</span><div><h2>توضیحات</h2><p>هر جزئیاتی که برای تیم اجرا مهم است بنویسید.</p></div></div><label><textarea name="message" rows="4" placeholder="مثلاً نوع چیدمان، حساسیت غذایی یا درخواست ویژه">{{ old('message',$reservation->message) }}</textarea></label></section>
<div class="booking-submit"><button class="btn" type="submit">{{ $reservation->exists?'ذخیره و صدور پیش‌فاکتور جدید':'ثبت درخواست و پیش‌فاکتور' }}</button><span>ثبت درخواست به معنی رزرو قطعی نیست.</span></div>
</form>
<aside class="price-sidebar"><div class="price-box"><span class="eyebrow">محاسبه زنده</span><h2>برآورد مراسم</h2><div class="price-loading" data-price-state>تاریخ و انتخاب‌ها را تکمیل کنید.</div><div class="price-breakdown" data-price-breakdown hidden></div><div class="price-total"><span>مبلغ نهایی</span><b data-price-total>—</b><small>تومان</small></div><p>عدد قطعی هنگام ثبت دوباره در سرور محاسبه می‌شود؛ تغییر HTML یا JavaScript اثری بر مبلغ ذخیره‌شده ندارد.</p></div><div class="secure-note">✦ قیمت هر رزرو Snapshot می‌شود؛ تغییر قیمت‌های آینده، پیش‌فاکتور قبلی را تغییر نمی‌دهد.</div></aside>
</div></section>
@endsection
