@extends('layouts.app')
@section('title','رزرو '.$reservation->tracking_code.' | تالارتو')
@section('content')
<section class="account-head"><div class="container"><div><span class="eyebrow">{{ $reservation->tracking_code }}</span><h1>{{ $reservation->event_type }} · {{ $reservation->date_jalali }}</h1><p>{{ number_format($reservation->guest_count) }} مهمان · سانس {{ $reservation->time_slot==='day'?'روز':'شب' }}</p></div><div class="head-actions">@if(in_array($reservation->status,['new','contacted']) && (int)$reservation->paid_amount===0)<a class="btn ghost" href="{{ route('account.reservations.edit',$reservation) }}">ویرایش انتخاب‌ها</a>@endif<a class="account-back" href="{{ route('account.dashboard') }}">پنل من</a></div></div></section>
<section class="section"><div class="container reservation-detail">
<div class="detail-main"><div class="panel-card"><div class="panel-title"><div><span class="eyebrow">وضعیت</span><h2>پیگیری رزرو</h2></div><span class="status-pill status-{{ $reservation->status }}">{{ ['new'=>'در انتظار بررسی','contacted'=>'تماس گرفته شد','confirmed'=>'رزرو قطعی','cancelled'=>'لغو شده','done'=>'برگزار شده'][$reservation->status]??$reservation->status }}</span></div><div class="progress-steps"><div class="done"><i>✓</i><span>اطلاعات ثبت شد</span></div><div class="{{ $reservation->latestQuote?->accepted_at?'done':'' }}"><i>{{ $reservation->latestQuote?->accepted_at?'✓':'2' }}</i><span>تأیید پیش‌فاکتور</span></div><div class="{{ $reservation->status==='confirmed'||$reservation->status==='done'?'done':'' }}"><i>{{ $reservation->status==='confirmed'||$reservation->status==='done'?'✓':'3' }}</i><span>رزرو قطعی</span></div><div class="{{ $reservation->payment_status==='paid'?'done':'' }}"><i>{{ $reservation->payment_status==='paid'?'✓':'4' }}</i><span>تسویه</span></div></div></div>
<div class="panel-card"><div class="panel-title"><div><span class="eyebrow">ریز قیمت</span><h2>پیش‌فاکتور نسخه {{ $reservation->latestQuote?->version??1 }}</h2><a href="{{ route('account.reservations.print-quote',$reservation) }}" target="_blank" rel="noopener">چاپ / PDF</a></div><b>{{ number_format($reservation->final_price) }} تومان</b></div><div class="invoice-lines">@foreach($reservation->items as $item)<div class="invoice-line"><div><b>{{ $item->title_snapshot }}</b><span>{{ number_format((float)$item->quantity,0) }} × {{ number_format(abs($item->unit_price)) }}</span></div><strong class="{{ $item->total_price<0?'negative':'' }}">{{ $item->total_price<0?'-':'' }}{{ number_format(abs($item->total_price)) }}</strong></div>@endforeach<div class="invoice-line total"><span>جمع نهایی</span><strong>{{ number_format($reservation->final_price) }} تومان</strong></div></div>@if($reservation->latestQuote && !$reservation->latestQuote->accepted_at && in_array($reservation->status,['new','contacted']))<form method="post" action="{{ route('account.reservations.accept-quote',$reservation) }}">@csrf<label class="inline-check"><input type="checkbox" name="accept_terms" value="1" required> قوانین و جزئیات پیش‌فاکتور این نسخه را مطالعه و تأیید می‌کنم.</label><button class="btn full" type="submit">تأیید این پیش‌فاکتور</button></form>@elseif($reservation->latestQuote?->accepted_at)<div class="accepted-note">✓ این پیش‌فاکتور توسط شما تأیید شده است.</div>@endif</div>
<div class="panel-card"><div class="panel-title"><div><span class="eyebrow">پرداخت‌ها</span><h2>تاریخچه مالی</h2></div></div>@forelse($reservation->payments as $payment)<div class="payment-row"><div><b>{{ number_format($payment->amount) }} تومان</b><span>{{ $payment->method }} · {{ \App\Support\JalaliDate::formatDateTime($payment->paid_at) }}</span></div><span class="status-pill">{{ $payment->status==='paid'?'پرداخت شده':$payment->status }}</span></div>@empty<p class="muted">هنوز پرداختی ثبت نشده است.</p>@endforelse</div></div>
<aside class="detail-side"><div class="money-card"><span>مبلغ قرارداد فعلی</span><b>{{ number_format($reservation->final_price) }}</b><small>تومان</small><div class="money-split"><div><span>پرداخت‌شده</span><strong>{{ number_format($reservation->paid_amount) }}</strong></div><div><span>مانده</span><strong>{{ number_format($reservation->balance) }}</strong></div></div></div><div class="panel-card mini-facts"><div><span>پکیج</span><b>{{ $reservation->package?->title??'—' }}</b></div><div><span>تعداد مهمان</span><b>{{ number_format($reservation->guest_count) }}</b></div><div><span>سانس</span><b>{{ $reservation->time_slot==='day'?'روز':'شب' }}</b></div><div><span>وضعیت مالی</span><b>{{ ['unpaid'=>'پرداخت نشده','partial'=>'بخشی پرداخت شده','paid'=>'تسویه'][$reservation->payment_status]??$reservation->payment_status }}</b></div></div>@if(!in_array($reservation->status,['cancelled','done','confirmed']))<form method="post" action="{{ route('account.reservations.cancel',$reservation) }}" onsubmit="return confirm('درخواست رزرو لغو شود؟')">@csrf<button class="danger full-danger" type="submit">لغو درخواست</button></form>@endif</aside>
</div></section>
@endsection
