<?php
use App\Http\Controllers\{AdminController,MediaLibraryController,AuthController,AvailabilityController,CommerceAdminController,CustomerDashboardController,CustomerProfileController,CustomerReservationController,HomeController,LeadController,PageController,PricePreviewController,SeoController};
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [PageController::class, 'about'])->name('about');
Route::get('/services', [PageController::class, 'services'])->name('services.index');
Route::get('/services/{service:slug}', [PageController::class, 'service'])->name('services.show');
Route::get('/packages', [PageController::class, 'packages'])->name('packages');
Route::get('/menu', [PageController::class, 'menu'])->name('menu');
Route::get('/gallery', [PageController::class, 'gallery'])->name('gallery');
Route::get('/calendar', [PageController::class, 'calendar'])->name('calendar');
Route::get('/calculator', [PageController::class, 'calculator'])->name('calculator');
Route::post('/price-preview',PricePreviewController::class)->name('public.price-preview')->middleware('throttle:30,1');
Route::get('/availability',AvailabilityController::class)->name('availability.check')->middleware('throttle:60,1');
Route::post('/reservation/request', [LeadController::class, 'reservation'])->name('reservation.legacy')->middleware('throttle:8,1');
Route::post('/visit-request', [LeadController::class, 'visit'])->name('visit.store')->middleware('throttle:8,1');
Route::get('/faq', [PageController::class, 'faq'])->name('faq');
Route::get('/contact', [PageController::class, 'contact'])->name('contact');
Route::post('/contact', [LeadController::class, 'contact'])->name('contact.store')->middleware('throttle:6,1');
Route::post('/review', [LeadController::class, 'testimonial'])->name('review.store')->middleware('throttle:3,10');
Route::get('/terms', [PageController::class, 'terms'])->name('terms');
Route::get('/privacy', [PageController::class, 'privacy'])->name('privacy');
Route::get('/blog', [PageController::class, 'blog'])->name('blog.index');
Route::get('/blog/{post:slug}', [PageController::class, 'post'])->name('blog.show');
Route::get('/sitemap.xml', [SeoController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', [SeoController::class, 'robots'])->name('robots');

Route::middleware('guest')->group(function(){
 Route::get('/login',[AuthController::class,'loginForm'])->name('login');
 Route::post('/login',[AuthController::class,'login'])->name('login.store')->middleware('throttle:8,1');
 Route::get('/register',[AuthController::class,'registerForm'])->name('register');
 Route::post('/register',[AuthController::class,'register'])->name('register.store')->middleware('throttle:5,1');
});
Route::post('/logout',[AuthController::class,'logout'])->name('logout')->middleware('auth');

Route::middleware('auth')->group(function(){
 Route::get('/reservation',[CustomerReservationController::class,'create'])->name('reservation');
 Route::prefix('account')->name('account.')->group(function(){
  Route::get('/',[CustomerDashboardController::class,'index'])->name('dashboard');
  Route::get('/profile',[CustomerProfileController::class,'edit'])->name('profile');
  Route::patch('/profile',[CustomerProfileController::class,'update'])->name('profile.update');
  Route::put('/profile/password',[CustomerProfileController::class,'password'])->name('profile.password');
  Route::get('/reservations',[CustomerReservationController::class,'index'])->name('reservations.index');
  Route::get('/reservations/create',[CustomerReservationController::class,'create'])->name('reservations.create');
  Route::post('/reservations',[CustomerReservationController::class,'store'])->name('reservations.store');
  Route::get('/reservations/{reservation}',[CustomerReservationController::class,'show'])->name('reservations.show');
  Route::get('/reservations/{reservation}/edit',[CustomerReservationController::class,'edit'])->name('reservations.edit');
  Route::get('/reservations/{reservation}/quote/print',[CustomerReservationController::class,'printQuote'])->name('reservations.print-quote');
  Route::put('/reservations/{reservation}',[CustomerReservationController::class,'update'])->name('reservations.update');
  Route::post('/reservations/{reservation}/accept-quote',[CustomerReservationController::class,'acceptQuote'])->name('reservations.accept-quote');
  Route::post('/reservations/{reservation}/cancel',[CustomerReservationController::class,'cancel'])->name('reservations.cancel');
  Route::post('/price-preview',PricePreviewController::class)->name('price-preview')->middleware('throttle:30,1');
 });
});

Route::get('/admin/login', [AdminController::class, 'login'])->name('admin.login');
Route::post('/admin/login', [AdminController::class, 'authenticate'])->name('admin.authenticate')->middleware('throttle:5,1');
Route::middleware(['admin','admin.panel'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::post('/logout', [AdminController::class, 'logout'])->name('logout');
    Route::get('/commerce',[CommerceAdminController::class,'index'])->name('commerce');
    Route::get('/commerce/reservations/export',[CommerceAdminController::class,'exportReservations'])->name('commerce.reservations.export');
    Route::post('/commerce/addons',[CommerceAdminController::class,'storeAddon'])->name('commerce.addons.store');
    Route::put('/commerce/addons/{addon}',[CommerceAdminController::class,'updateAddon'])->name('commerce.addons.update');
    Route::delete('/commerce/addons/{addon}',[CommerceAdminController::class,'deleteAddon'])->name('commerce.addons.delete');
    Route::post('/commerce/rules',[CommerceAdminController::class,'storeRule'])->name('commerce.rules.store');
    Route::put('/commerce/rules/{pricingRule}',[CommerceAdminController::class,'updateRule'])->name('commerce.rules.update');
    Route::delete('/commerce/rules/{pricingRule}',[CommerceAdminController::class,'deleteRule'])->name('commerce.rules.delete');
    Route::post('/commerce/reservations/{reservation}/payments',[CommerceAdminController::class,'storePayment'])->name('commerce.payments.store');
    Route::post('/commerce/reservations/{reservation}/confirm',[CommerceAdminController::class,'confirm'])->name('commerce.reservations.confirm');
    Route::put('/settings', [AdminController::class, 'settings'])->name('settings');
    Route::post('/services', [AdminController::class, 'storeService'])->name('services.store');
    Route::put('/services/{service}', [AdminController::class, 'updateService'])->name('services.update');
    Route::delete('/services/{service}', [AdminController::class, 'deleteService'])->name('services.delete');
    Route::post('/packages', [AdminController::class, 'storePackage'])->name('packages.store');
    Route::put('/packages/{package}', [AdminController::class, 'updatePackage'])->name('packages.update');
    Route::delete('/packages/{package}', [AdminController::class, 'deletePackage'])->name('packages.delete');
    Route::post('/menu-items', [AdminController::class, 'storeMenu'])->name('menu.store');
    Route::put('/menu-items/{menuItem}', [AdminController::class, 'updateMenu'])->name('menu.update');
    Route::delete('/menu-items/{menuItem}', [AdminController::class, 'deleteMenu'])->name('menu.delete');
    Route::post('/media', [MediaLibraryController::class, 'store'])->name('media.store');
    Route::post('/media/import', [MediaLibraryController::class, 'importZip'])->name('media.import');
    Route::patch('/media/{mediaAsset}', [MediaLibraryController::class, 'update'])->name('media.update');
    Route::post('/media/{mediaAsset}/hero', [MediaLibraryController::class, 'setHero'])->name('media.hero');
    Route::post('/media/{mediaAsset}/about', [MediaLibraryController::class, 'setAbout'])->name('media.about');
    Route::delete('/media/{mediaAsset}', [MediaLibraryController::class, 'destroy'])->name('media.delete');
    Route::post('/gallery', [AdminController::class, 'storeGallery'])->name('gallery.store');
    Route::delete('/gallery/{galleryItem}', [AdminController::class, 'deleteGallery'])->name('gallery.delete');
    Route::post('/posts', [AdminController::class, 'storePost'])->name('posts.store');
    Route::put('/posts/{post}', [AdminController::class, 'updatePost'])->name('posts.update');
    Route::delete('/posts/{post}', [AdminController::class, 'deletePost'])->name('posts.delete');
    Route::post('/faqs', [AdminController::class, 'storeFaq'])->name('faqs.store');
    Route::put('/faqs/{faq}', [AdminController::class, 'updateFaq'])->name('faqs.update');
    Route::delete('/faqs/{faq}', [AdminController::class, 'deleteFaq'])->name('faqs.delete');
    Route::post('/calendar', [AdminController::class, 'storeCalendar'])->name('calendar.store');
    Route::delete('/calendar/{calendarDate}', [AdminController::class, 'deleteCalendar'])->name('calendar.delete');
    Route::patch('/reservations/{reservation}', [CommerceAdminController::class, 'status'])->name('reservations.status');
    Route::patch('/visits/{visitRequest}', [AdminController::class, 'visitStatus'])->name('visits.status');
    Route::patch('/contacts/{contactMessage}', [AdminController::class, 'contactStatus'])->name('contacts.status');
    Route::patch('/testimonials/{testimonial}', [AdminController::class, 'testimonialStatus'])->name('testimonials.status');
});
