<?php
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\SeoController;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [PageController::class, 'about'])->name('about');
Route::get('/services', [PageController::class, 'services'])->name('services.index');
Route::get('/services/{service:slug}', [PageController::class, 'service'])->name('services.show');
Route::get('/packages', [PageController::class, 'packages'])->name('packages');
Route::get('/menu', [PageController::class, 'menu'])->name('menu');
Route::get('/gallery', [PageController::class, 'gallery'])->name('gallery');
Route::get('/calendar', [PageController::class, 'calendar'])->name('calendar');
Route::get('/calculator', [PageController::class, 'calculator'])->name('calculator');
Route::get('/reservation', [PageController::class, 'reservation'])->name('reservation');
Route::post('/reservation', [LeadController::class, 'reservation'])->name('reservation.store')->middleware('throttle:8,1');
Route::post('/visit-request', [LeadController::class, 'visit'])->name('visit.store')->middleware('throttle:8,1');
Route::get('/faq', [PageController::class, 'faq'])->name('faq');
Route::get('/contact', [PageController::class, 'contact'])->name('contact');
Route::post('/contact', [LeadController::class, 'contact'])->name('contact.store')->middleware('throttle:6,1');
Route::post('/review', [LeadController::class, 'testimonial'])->name('review.store')->middleware('throttle:3,10');
Route::get('/terms', [PageController::class, 'terms'])->name('terms');
Route::get('/privacy', [PageController::class, 'privacy'])->name('privacy');
Route::get('/blog', [PageController::class, 'blog'])->name('blog.index');
Route::get('/blog/{post:slug}', [PageController::class, 'post'])->name('blog.show');
Route::get('/sitemap.xml', [SeoController::class, 'sitemap'])->name('sitemap');
Route::get('/robots.txt', [SeoController::class, 'robots'])->name('robots');

Route::get('/admin/login', [AdminController::class, 'login'])->name('admin.login');
Route::post('/admin/login', [AdminController::class, 'authenticate'])->name('admin.authenticate')->middleware('throttle:5,1');
Route::middleware('admin')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::post('/logout', [AdminController::class, 'logout'])->name('logout');
    Route::put('/settings', [AdminController::class, 'settings'])->name('settings');
    Route::post('/services', [AdminController::class, 'storeService'])->name('services.store');
    Route::put('/services/{service}', [AdminController::class, 'updateService'])->name('services.update');
    Route::delete('/services/{service}', [AdminController::class, 'deleteService'])->name('services.delete');
    Route::post('/packages', [AdminController::class, 'storePackage'])->name('packages.store');
    Route::put('/packages/{package}', [AdminController::class, 'updatePackage'])->name('packages.update');
    Route::delete('/packages/{package}', [AdminController::class, 'deletePackage'])->name('packages.delete');
    Route::post('/menu-items', [AdminController::class, 'storeMenu'])->name('menu.store');
    Route::put('/menu-items/{menuItem}', [AdminController::class, 'updateMenu'])->name('menu.update');
    Route::delete('/menu-items/{menuItem}', [AdminController::class, 'deleteMenu'])->name('menu.delete');
    Route::post('/gallery', [AdminController::class, 'storeGallery'])->name('gallery.store');
    Route::delete('/gallery/{galleryItem}', [AdminController::class, 'deleteGallery'])->name('gallery.delete');
    Route::post('/posts', [AdminController::class, 'storePost'])->name('posts.store');
    Route::put('/posts/{post}', [AdminController::class, 'updatePost'])->name('posts.update');
    Route::delete('/posts/{post}', [AdminController::class, 'deletePost'])->name('posts.delete');
    Route::post('/faqs', [AdminController::class, 'storeFaq'])->name('faqs.store');
    Route::put('/faqs/{faq}', [AdminController::class, 'updateFaq'])->name('faqs.update');
    Route::delete('/faqs/{faq}', [AdminController::class, 'deleteFaq'])->name('faqs.delete');
    Route::post('/calendar', [AdminController::class, 'storeCalendar'])->name('calendar.store');
    Route::delete('/calendar/{calendarDate}', [AdminController::class, 'deleteCalendar'])->name('calendar.delete');
    Route::patch('/reservations/{reservation}', [AdminController::class, 'reservationStatus'])->name('reservations.status');
    Route::patch('/visits/{visitRequest}', [AdminController::class, 'visitStatus'])->name('visits.status');
    Route::patch('/contacts/{contactMessage}', [AdminController::class, 'contactStatus'])->name('contacts.status');
    Route::patch('/testimonials/{testimonial}', [AdminController::class, 'testimonialStatus'])->name('testimonials.status');
});