<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('ceremony_services',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->text('short_description')->nullable();$t->longText('description')->nullable();$t->text('image')->nullable();$t->string('icon',30)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('active')->default(true);$t->timestamps();});
 Schema::create('packages',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->string('subtitle')->nullable();$t->unsignedBigInteger('base_price')->default(0);$t->unsignedBigInteger('per_guest_price')->default(0);$t->unsignedInteger('min_guests')->default(0);$t->text('description')->nullable();$t->json('features')->nullable();$t->boolean('featured')->default(false);$t->boolean('active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('menu_items',function(Blueprint $t){$t->id();$t->string('category');$t->string('title');$t->text('description')->nullable();$t->unsignedBigInteger('price_per_guest')->default(0);$t->boolean('active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('gallery_items',function(Blueprint $t){$t->id();$t->string('title')->nullable();$t->string('category');$t->text('image');$t->text('video_url')->nullable();$t->boolean('active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
 Schema::create('testimonials',function(Blueprint $t){$t->id();$t->string('name');$t->string('event_type')->nullable();$t->text('body');$t->unsignedTinyInteger('rating')->default(5);$t->string('status')->default('pending');$t->timestamps();});
 Schema::create('posts',function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->longText('body');$t->text('cover_image')->nullable();$t->string('meta_title')->nullable();$t->string('meta_description',320)->nullable();$t->timestamp('published_at')->nullable();$t->timestamps();});
 Schema::create('faqs',function(Blueprint $t){$t->id();$t->string('question',500);$t->text('answer');$t->unsignedInteger('sort_order')->default(0);$t->boolean('active')->default(true);$t->timestamps();});
 }public function down():void{foreach(['faqs','posts','testimonials','gallery_items','menu_items','packages','ceremony_services'] as $table)Schema::dropIfExists($table);}};
