<?php
namespace App\Http\Controllers;
use App\Models\{AdminUser,MediaAsset,SiteSetting,CeremonyService,Package,MenuItem,GalleryItem,Reservation,VisitRequest,Testimonial,Post,Faq,CalendarDate,ContactMessage};
use App\Support\{JalaliDate,UploadImage};
use Illuminate\Http\Request; use Illuminate\Support\Str; use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
class AdminController extends Controller {
 public function login(){if(session('admin_user_id')&&AdminUser::whereKey(session('admin_user_id'))->where('active',true)->exists())return redirect()->route('admin.dashboard');return view('admin.login');}
 public function authenticate(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|string']);$admin=AdminUser::where('email',strtolower($d['email']))->where('active',true)->first();if(!$admin||!Hash::check($d['password'],$admin->password))return back()->withErrors(['email'=>'اطلاعات ورود نادرست است.'])->onlyInput('email');$r->session()->regenerate();$r->session()->put('admin_user_id',$admin->id);return redirect()->route('admin.dashboard');}
 public function logout(Request $r){$r->session()->invalidate();$r->session()->regenerateToken();return redirect()->route('admin.login');}
 public function dashboard(Request $r){
 $reservationQuery=Reservation::with('package')->latest();
 if($r->filled('rq')){
  $query=mb_substr(trim((string)$r->input('rq')),0,100);
  $reservationQuery->where(fn($b)=>$b->where('name','like','%'.$query.'%')->orWhere('mobile','like','%'.$query.'%')->orWhere('tracking_code','like','%'.$query.'%'));
 }
 return view('admin.dashboard',['settings'=>SiteSetting::firstOrCreate([]),'services'=>CeremonyService::orderBy('sort_order')->get(),'packages'=>Package::orderBy('sort_order')->get(),'menuItems'=>MenuItem::orderBy('category')->orderBy('sort_order')->get(),'gallery'=>GalleryItem::orderBy('sort_order')->get(),'mediaAssets'=>MediaAsset::orderBy('sort_order')->orderBy('id')->get(),'reservations'=>Reservation::with('package')->latest()->take(100)->get(),'reservationPage'=>$reservationQuery->paginate(30,['*'],'admin_reservations_page')->withQueryString(),'visits'=>VisitRequest::latest()->take(100)->get(),'contacts'=>ContactMessage::latest()->take(100)->get(),'testimonials'=>Testimonial::latest()->get(),'posts'=>Post::latest()->get(),'faqs'=>Faq::orderBy('sort_order')->get(),'calendarDates'=>CalendarDate::orderByDesc('date')->take(180)->get(),'stats'=>['reservations'=>Reservation::count(),'new'=>Reservation::where('status','new')->count(),'confirmed'=>Reservation::where('status','confirmed')->count(),'visits'=>VisitRequest::where('status','new')->count()]]);}
 public function settings(Request $r){$d=$r->validate(['site_name'=>'required|string|max:120','phone'=>'nullable|string|max:30','whatsapp'=>'nullable|string|max:30','instagram'=>'nullable|string|max:120','address'=>'nullable|string|max:500','map_embed'=>'nullable|string|max:5000','hero_title'=>'required|string|max:180','hero_subtitle'=>'nullable|string|max:500','hero_image_url'=>'nullable|url|max:1000','hero_image_file'=>'nullable|image|max:6144','about_title'=>'nullable|string|max:180','about_body'=>'nullable|string|max:5000','about_image_url'=>'nullable|url|max:1000','about_image_file'=>'nullable|image|max:6144','capacity_min'=>'nullable|integer|min:0','capacity_max'=>'nullable|integer|min:0|gte:capacity_min','parking_capacity'=>'nullable|integer|min:0','amenities'=>'nullable|string|max:5000','seo_title'=>'nullable|string|max:180','seo_description'=>'nullable|string|max:320']);$s=SiteSetting::firstOrCreate([]);$hero=UploadImage::store($r->file('hero_image_file'),'site');$about=UploadImage::store($r->file('about_image_file'),'site');$d['hero_image']=$hero?:(($d['hero_image_url']??null)?:$s->hero_image);$d['about_image']=$about?:(($d['about_image_url']??null)?:$s->about_image);unset($d['hero_image_url'],$d['hero_image_file'],$d['about_image_url'],$d['about_image_file']);$d['amenities']=array_values(array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)$r->input('amenities')))));$s->update($d);return back()->with('success','تنظیمات ذخیره شد.');}
 private function serviceData(Request $r,?CeremonyService $service=null):array{$d=$r->validate(['title'=>'required|string|max:150','slug'=>['nullable','string','max:160',Rule::unique('ceremony_services','slug')->ignore($service?->id)],'short_description'=>'nullable|string|max:500','description'=>'nullable|string|max:5000','image_url'=>'nullable|url|max:1000','image_file'=>'nullable|image|max:6144','icon'=>'nullable|string|max:30','sort_order'=>'nullable|integer|min:0']);$d['slug']=($d['slug']??null)?:($service?->slug ?: Str::slug($d['title']).'-'.Str::lower(Str::random(4)));$upload=UploadImage::store($r->file('image_file'),'services');$d['image']=$upload?:(($d['image_url']??null)?:$service?->image);unset($d['image_url'],$d['image_file']);$d['active']=$r->boolean('active');return $d;}
 public function storeService(Request $r){CeremonyService::create($this->serviceData($r));return back()->with('success','خدمت اضافه شد.');}
 public function updateService(Request $r,CeremonyService $service){$service->update($this->serviceData($r,$service));return back()->with('success','خدمت ویرایش شد.');}
 public function deleteService(CeremonyService $service){UploadImage::delete($service->image);$service->delete();return back();}
 private function packageData(Request $r,?Package $package=null):array{$d=$r->validate(['title'=>'required|string|max:150','slug'=>['nullable','string','max:160',Rule::unique('packages','slug')->ignore($package?->id)],'subtitle'=>'nullable|string|max:300','base_price'=>'nullable|integer|min:0','per_guest_price'=>'nullable|integer|min:0','min_guests'=>'nullable|integer|min:0','description'=>'nullable|string|max:3000','features'=>'nullable|string|max:3000','sort_order'=>'nullable|integer|min:0']);$d['slug']=($d['slug']??null)?:($package?->slug ?: Str::slug($d['title']).'-'.Str::lower(Str::random(4)));$d['features']=array_values(array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)$r->input('features')))));$d['featured']=$r->boolean('featured');$d['active']=$r->boolean('active');return $d;}
 public function storePackage(Request $r){Package::create($this->packageData($r));return back()->with('success','پکیج اضافه شد.');} public function updatePackage(Request $r,Package $package){$package->update($this->packageData($r,$package));return back()->with('success','پکیج ویرایش شد.');} public function deletePackage(Package $package){$package->delete();return back();}
 private function menuData(Request $r):array{$d=$r->validate(['category'=>'required|string|max:80','title'=>'required|string|max:150','description'=>'nullable|string|max:500','price_per_guest'=>'nullable|integer|min:0','sort_order'=>'nullable|integer|min:0']);$d['active']=$r->boolean('active');return $d;} public function storeMenu(Request $r){MenuItem::create($this->menuData($r));return back()->with('success','آیتم منو اضافه شد.');} public function updateMenu(Request $r,MenuItem $menuItem){$menuItem->update($this->menuData($r));return back()->with('success','منو ویرایش شد.');} public function deleteMenu(MenuItem $menuItem){$menuItem->delete();return back();}
 public function storeGallery(Request $r){
  $d=$r->validate(['title'=>'nullable|string|max:150','category'=>'required|string|max:80','image_url'=>'nullable|url|max:1000','image_file'=>'nullable|image|max:8192','video_url'=>'nullable|url|max:1000','sort_order'=>'nullable|integer|min:0']);
  $url=UploadImage::store($r->file('image_file'),'gallery')?:($d['image_url']??null);
  if(!$url)return back()->withErrors(['image_file'=>'تصویر یا آدرس معتبر وارد کنید.']);
  $title=($d['title']??null)?:'تصویر مراسم';$active=$r->boolean('active');
  DB::transaction(function()use($d,$url,$title,$active,$r){
   $item=GalleryItem::create(['title'=>$title,'category'=>$d['category'],'image'=>$url,'video_url'=>$d['video_url']??null,'sort_order'=>$d['sort_order']??0,'active'=>$active]);
   $dimensions=$r->file('image_file')?@getimagesize($r->file('image_file')->getRealPath()):null;
   MediaAsset::create(['gallery_item_id'=>$item->id,'title'=>$title,'alt_text'=>$title,'category'=>$d['category'],'url'=>$url,'source'=>'uploaded',
    'bytes'=>$r->file('image_file')?->getSize()??0,'width'=>$dimensions[0]??null,'height'=>$dimensions[1]??null,'sort_order'=>$d['sort_order']??0,'active'=>$active]);
  });
  return back()->with('success','تصویر اضافه شد.')->withFragment('admin-gallery');
 }
 public function deleteGallery(GalleryItem $galleryItem){
  $url=$galleryItem->image;
  if(SiteSetting::where('hero_image',$url)->orWhere('about_image',$url)->exists())
   throw ValidationException::withMessages(['image'=>'این تصویر برای بنر یا معرفی استفاده می‌شود؛ ابتدا تصویر جایگزین انتخاب کنید.']);
  DB::transaction(function()use($galleryItem){
   MediaAsset::where('gallery_item_id',$galleryItem->id)->delete();
   $galleryItem->delete();
  });
  if(!MediaAsset::where('url',$url)->exists()&&!GalleryItem::where('image',$url)->exists())UploadImage::delete($url);
  return back()->with('success','تصویر حذف شد.')->withFragment('admin-gallery');
 }
 private function postData(Request $r,?Post $post=null):array{$d=$r->validate(['title'=>'required|string|max:180','slug'=>['nullable','string','max:190',Rule::unique('posts','slug')->ignore($post?->id)],'excerpt'=>'nullable|string|max:500','body'=>'required|string|max:30000','cover_image_url'=>'nullable|url|max:1000','cover_image_file'=>'nullable|image|max:8192','meta_title'=>'nullable|string|max:180','meta_description'=>'nullable|string|max:320']);$d['slug']=($d['slug']??null)?:($post?->slug ?: Str::slug($d['title']).'-'.Str::lower(Str::random(4)));$upload=UploadImage::store($r->file('cover_image_file'),'posts');$d['cover_image']=$upload?:(($d['cover_image_url']??null)?:$post?->cover_image);unset($d['cover_image_url'],$d['cover_image_file']);$d['published_at']=$r->boolean('published')?($post?->published_at?:now()):null;return $d;}
 public function storePost(Request $r){Post::create($this->postData($r));return back()->with('success','مقاله اضافه شد.');} public function updatePost(Request $r,Post $post){$post->update($this->postData($r,$post));return back()->with('success','مقاله ویرایش شد.');} public function deletePost(Post $post){UploadImage::delete($post->cover_image);$post->delete();return back();}
 private function faqData(Request $r):array{$d=$r->validate(['question'=>'required|string|max:500','answer'=>'required|string|max:3000','sort_order'=>'nullable|integer|min:0']);$d['active']=$r->boolean('active');return $d;} public function storeFaq(Request $r){Faq::create($this->faqData($r));return back();} public function updateFaq(Request $r,Faq $faq){$faq->update($this->faqData($r));return back();} public function deleteFaq(Faq $faq){$faq->delete();return back();}
 public function storeCalendar(Request $r){$r->merge(['date_jalali'=>JalaliDate::normalize($r->input('date_jalali'))]);$d=$r->validate(['date_jalali'=>'required|string','status'=>'required|in:booked,unavailable,special','note'=>'nullable|string|max:300']);try{$date=JalaliDate::toCarbon($d['date_jalali']);}catch(\Throwable){return back()->withErrors(['date_jalali'=>'تاریخ معتبر نیست.']);}CalendarDate::updateOrCreate(['date'=>$date->toDateString()],['status'=>$d['status'],'note'=>$d['note']??null]);return back()->with('success','تقویم به‌روزرسانی شد.');} public function deleteCalendar(CalendarDate $calendarDate){$calendarDate->delete();return back();}
 public function reservationStatus(Request $r,Reservation $reservation,\App\Services\AvailabilityService $availability){ return app(CommerceAdminController::class)->status($r,$reservation,$availability); }
 public function visitStatus(Request $r,VisitRequest $visitRequest){$d=$r->validate(['status'=>'required|in:new,contacted,scheduled,done,cancelled','admin_note'=>'nullable|string|max:2000']);$visitRequest->update($d);return back();} public function contactStatus(Request $r,ContactMessage $contactMessage){$d=$r->validate(['status'=>'required|in:new,read,closed']);$contactMessage->update($d);return back();} public function testimonialStatus(Request $r,Testimonial $testimonial){$d=$r->validate(['status'=>'required|in:pending,approved,rejected']);$testimonial->update($d);return back();}
}
