<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title', $siteSettings?->seo_title ?: 'تالارتو')</title><meta name="description" content="@yield('meta_description', $siteSettings?->seo_description ?: 'تالار و مجموعه برگزاری مراسم')"><link rel="canonical" href="{{ url()->current() }}">@if(request()->is('account*')||request()->is('admin*')||request()->is('login')||request()->is('register')||request()->is('reservation'))<meta name="robots" content="noindex,nofollow">@endif
<meta property="og:type" content="website"><meta property="og:title" content="@yield('title', $siteSettings?->seo_title ?: 'تالارتو')"><meta property="og:description" content="@yield('meta_description', $siteSettings?->seo_description ?: '')"><meta property="og:url" content="{{ url()->current() }}">
<link rel="icon" type="image/png" href="{{ asset('assets/venue/favicon.png') }}"><link rel="apple-touch-icon" href="{{ asset('assets/venue/logo.png') }}"><link rel="stylesheet" href="{{ asset('assets/css/app.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/portal.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/luxury.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/fidelity.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/form-system.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/customer-experience.css') }}">@if(request()->is('admin*'))<link rel="stylesheet" href="{{ asset('assets/css/admin-neutral.css') }}?v=1">@endif@stack('head')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'EventVenue','name'=>$siteSettings?->site_name?:'تالارتو','telephone'=>$siteSettings?->phone,'address'=>$siteSettings?->address,'url'=>url('/')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
</head><body>
<header class="mw-site-header"><div class="mw-header-inner">
<nav class="mw-site-links" data-menu><a href="{{ route('home') }}" @class(['current'=>request()->routeIs('home')])>صفحه اصلی</a><a href="{{ route('about') }}">درباره ما</a><a href="{{ route('services.index') }}">خدمات</a><a href="{{ route('gallery') }}">گالری</a><a href="{{ route('contact') }}">تماس با ما</a></nav>
<a href="{{ route('home') }}" class="mw-header-logo"><img src="{{ asset('assets/venue/logo.png') }}" alt="نشان تالار رویای ماندگار"></a>
<div class="mw-header-actions"><div class="mw-header-contact"><b>{{ ($siteSettings?->phone && !str_contains($siteSettings->phone,'000000'))?$siteSettings->phone:'مشاوره و رزرو' }}</b><small>هماهنگی و بازدید از مجموعه</small></div><a class="mw-header-reserve" href="{{ route('reservation') }}">▦ &nbsp; رزرو بازدید</a>@auth<a class="mw-header-user" href="{{ route('account.dashboard') }}" title="پنل کاربری">◉</a>@else<a class="mw-header-user" href="{{ route('login') }}" title="ورود کاربر">◉</a>@endauth @if(session('admin_user_id'))<a class="mw-header-user" href="{{ route('admin.dashboard') }}" title="مدیریت">⚙</a>@endif</div>
<button class="mw-mobile-menu" type="button" data-menu-toggle aria-label="بازکردن منو">☰</button>
</div></header>
<main>@if(session('success'))<div class="container top-alert">{{ session('success') }}</div>@endif @if(session('info'))<div class="container top-alert info">{{ session('info') }}</div>@endif @if($errors->any())<div class="container top-alert error">{{ $errors->first() }}</div>@endif @yield('content')</main>
<footer class="mw-site-footer"><div class="mw-footer-top">
  <div class="mw-footer-brand"><img src="{{ asset('assets/venue/logo.png') }}" width="102" height="102" alt="لوگوی تالار رویای ماندگار"><h3>تالار رویای ماندگار</h3><p>هر مراسم، یک داستان ماندگار؛ میزبان لحظه‌های خاص شما در شمال تهران.</p><div class="mw-footer-links"><a href="{{ route('gallery') }}">▧</a><a href="{{ route('contact') }}">✉</a><a href="{{ route('reservation') }}">▦</a></div></div>
  <div class="mw-footer-column"><b>خدمات ما</b><a href="{{ route('services.index') }}">تشریفات مراسم</a><a href="{{ route('gallery') }}">دکوراسیون و گل‌آرایی</a><a href="{{ route('services.index') }}">نورپردازی و پذیرایی</a><a href="{{ route('reservation') }}">درخواست بازدید</a></div>
  <div class="mw-footer-column"><b>دسترسی سریع</b><a href="{{ route('home') }}">صفحه اصلی</a><a href="{{ route('about') }}">درباره ما</a><a href="{{ route('calendar') }}">تقویم رزرو</a><a href="{{ route('faq') }}">سوالات متداول</a><a href="{{ route('login') }}">پنل کاربری</a></div>
  <div class="mw-footer-location"><b>آدرس ما</b><p>تهران، زعفرانیه</p><p>نشانی دقیق هنگام هماهنگی بازدید اعلام می‌شود.</p><div class="mw-map-fallback"><span>⌖</span><b>زعفرانیه، تهران</b><small>جهت مشاهده مسیر روی نقشه کلیک کنید.</small></div><iframe loading="lazy" title="نقشه زعفرانیه تهران" src="https://maps.google.com/maps?q=Zafaraniyeh%20Tehran&t=&z=13&ie=UTF8&iwloc=&output=embed"></iframe><a href="https://www.google.com/maps/search/?api=1&query=Zafaraniyeh+Tehran" target="_blank" rel="noopener">مشاهده روی نقشه ←</a></div>
</div><div class="mw-footer-bottom"><span>© {{ \Morilog\Jalali\Jalalian::now()->format('Y') }} تالار رویای ماندگار — تمامی حقوق محفوظ است.</span><a href="https://redcoweb.ir" target="_blank" rel="noopener">ساخته شده توسط redcoweb.ir</a></div></footer>
<script src="{{ asset('assets/js/app.js') }}" defer></script><script src="{{ asset('assets/js/portal.js') }}" defer></script><script src="{{ asset('assets/js/public-price.js') }}" defer></script><script src="{{ asset('assets/js/availability.js') }}" defer></script><script src="{{ asset('assets/js/form-enhancements.js') }}" defer></script>@stack('scripts')</body></html>
