<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title', $siteSettings?->seo_title ?: 'تالارتو')</title><meta name="description" content="@yield('meta_description', $siteSettings?->seo_description ?: 'تالار و مجموعه برگزاری مراسم')"><link rel="canonical" href="{{ url()->current() }}">
<meta property="og:type" content="website"><meta property="og:title" content="@yield('title', $siteSettings?->seo_title ?: 'تالارتو')"><meta property="og:description" content="@yield('meta_description', $siteSettings?->seo_description ?: '')"><meta property="og:url" content="{{ url()->current() }}">
<link rel="stylesheet" href="{{ asset('assets/css/app.css') }}"><link rel="stylesheet" href="{{ asset('assets/css/portal.css') }}">@stack('head')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'EventVenue','name'=>$siteSettings?->site_name?:'تالارتو','telephone'=>$siteSettings?->phone,'address'=>$siteSettings?->address,'url'=>url('/')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
</head><body>
<header><div class="container nav"><a class="brand" href="{{ route('home') }}">تالار<span>تو</span></a><button class="menu-toggle" type="button" data-menu-toggle>☰</button><nav data-menu><a href="{{ route('services.index') }}">مراسم‌ها</a><a href="{{ route('packages') }}">پکیج‌ها</a><a href="{{ route('menu') }}">منو</a><a href="{{ route('gallery') }}">گالری</a><a href="{{ route('calendar') }}">تقویم</a><a href="{{ route('calculator') }}">محاسبه هزینه</a><a href="{{ route('blog.index') }}">مجله</a>@if(session('admin_authenticated'))<a href="{{ route('admin.commerce') }}">قیمت‌گذاری</a>@endif</nav><div class="nav-account">@auth<a class="account-link" href="{{ route('account.dashboard') }}">پنل من</a><form method="post" action="{{ route('logout') }}">@csrf<button class="nav-logout" type="submit">خروج</button></form>@else<a class="account-link" href="{{ route('login') }}">ورود</a><a class="btn small" href="{{ route('register') }}">ساخت حساب</a>@endauth</div></div></header>
<main>@if(session('success'))<div class="container top-alert">{{ session('success') }}</div>@endif @if(session('info'))<div class="container top-alert info">{{ session('info') }}</div>@endif @if($errors->any())<div class="container top-alert error">{{ $errors->first() }}</div>@endif @yield('content')</main>
<footer><div class="container footer"><div><a class="brand" href="{{ route('home') }}">تالار<span>تو</span></a><p>{{ $siteSettings?->hero_subtitle }}</p></div><div><b>دسترسی سریع</b><a href="{{ route('services.index') }}">خدمات مراسم</a><a href="{{ route('gallery') }}">گالری</a><a href="{{ route('calendar') }}">تقویم</a><a href="{{ route('calculator') }}">محاسبه هزینه</a><a href="{{ route('faq') }}">سوالات متداول</a><a href="{{ route('reservation') }}">رزرو آنلاین</a><a href="{{ route('terms') }}">قوانین رزرو</a><a href="{{ route('privacy') }}">حریم خصوصی</a></div><div><b>ارتباط</b><span>{{ $siteSettings?->phone }}</span><span>{{ $siteSettings?->address }}</span><span>Instagram: {{ $siteSettings?->instagram }}</span></div></div><div class="copyright">© {{ date('Y') }} تالارتو — تمامی حقوق محفوظ است.</div></footer>
<script src="{{ asset('assets/js/app.js') }}" defer></script><script src="{{ asset('assets/js/portal.js') }}" defer></script>@stack('scripts')</body></html>
